# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8

pipelines:
    branches:
        production:
            - step:
                  deployment: production
                  caches:
                      - node
                  script:
                      - npm install
                      - npm install -g @angular/cli
                      - node --max_old_space_size=4000 ./node_modules/@angular/cli/bin/ng build --prod
                      - scp -r ./dist/ root@app.blueplus.io:/var/www/blueplus-website/
